// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3K4bR-ixy2_fWPbylTn-f1_WnDrJ6XbA',
    appId: '1:182831517388:web:d42c1a4ab85e21f6027c69',
    messagingSenderId: '182831517388',
    projectId: 'safi-35aa6',
    authDomain: 'safi-35aa6.firebaseapp.com',
    storageBucket: 'safi-35aa6.firebasestorage.app',
    measurementId: 'G-CSHY11ECQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtmQ1awGIvowWRaIfM3Usbo2hMayQZbgM',
    appId: '1:182831517388:android:face6a414f12d062027c69',
    messagingSenderId: '182831517388',
    projectId: 'safi-35aa6',
    storageBucket: 'safi-35aa6.firebasestorage.app',
  );
}
